[workspace]
members = ["mini_udp", "derive"]
resolver = "3"

[workspace.package]
version = "0.4.0"
edition = "2024"
description = "A minimal implementation of a reliability protocol on top of UDP for game networking"
authors = ["faervan <faervan@proton.me>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/faervan/mini_udp"
keywords = ["gamedev", "udp", "networking", "reliable"]
categories = ["network-programming", "game-development"]
exclude = ["justfile"]

[workspace.dependencies]
mini_udp_derive = { path = "derive", version = "0.4.0" }

crc = "3.4"
rand = "0.10"

tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2"
enum-assoc = "1.3"
strum = { version = "0.28", features = ["derive"] }

# Proc macro libs
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "3.0", features = ["extra-traits"] }
