[package]
name = "mini_udp"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[features]
default = []

[dependencies]
mini_udp_derive.workspace = true

crc.workspace = true
rand.workspace = true
ringbuffer.workspace = true

tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
